ALTER TYPE public.audit_event_type ADD VALUE IF NOT EXISTS 'QUALITY_SCORE_RECALCULATED';
ALTER TYPE public.audit_event_type ADD VALUE IF NOT EXISTS 'QUALITY_WARNING_SET';
ALTER TYPE public.audit_event_type ADD VALUE IF NOT EXISTS 'QUALITY_WARNING_CLEARED';